
services:
  db:
    image: postgres:15
    container_name: forum_db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - forum_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env

  api:
    build: .
    container_name: forum_api
    environment:
      ASPNETCORE_URLS: "http://+:5146"
      ConnectionStrings__DefaultConnection: "Host=${DB_HOST};Port=${DB_PORT};Database=${DB_NAME};Username=${DB_USER};Password=${DB_PASSWORD}"
      JWT_KEY: "${JWT_KEY}"
      Jwt__Issuer: "${JWT_ISSUER}"
      Jwt__Audience: "${JWT_AUDIENCE}"
    depends_on:
      - db
    ports:
      - "5146:5146"
    volumes :
      - ./uploads:/app/uploads
    env_file:
      - .env
  
    

volumes:
  forum_data:
  forum_uploads:
